CREATE TABLE orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE goods (
    id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    good_id VARCHAR(255) NOT NULL,
    amount INT NOT NULL CHECK ( amount > 0 ),
    FOREIGN KEY (order_id) REFERENCES orders (id)
);